sequenceDiagram
    participant browser
    participant server

browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note
activate server
Note right of browser: Clicking the save button cause this HTTP POST request 
server-->>browser: HTML file
deactivate server
Note right of browser: The server respond with HTTP status code 302 (URL redirect)

browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/notes
activate server
Note right of browser: The browser perform HTML GET to the address defined on the header's location
server-->>browser: HTML file
deactivate server
Note right of browser: The browser load this HTML file, which cause the notes page to reload

browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
activate server

server-->>browser: CSS file
deactivate server

browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
activate server
server-->>browser: Javascript file
deactivate server

browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
activate server
server-->>browser: JSON file
deactivate server
